name: Android Build

on:
  push:
    # Triggers on push to every branch EXCEPT 'main'
    branches-ignore: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties

    - name: Clean Build
      run: ./gradlew clean --no-daemon

    - name: Build with Gradle
      run: ./gradlew assembleDebug --no-daemon --no-build-cache --stacktrace 2>&1 | tee build.log

    - name: Upload Build Logs
      if: failure()
      id: log_upload
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build.log

    - name: Rename APK
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        APK_NAME="${REPO_NAME}-build-${{ github.run_number }}.apk"
        mv app/build/outputs/apk/debug/app-debug.apk "app/build/outputs/apk/debug/$APK_NAME"
        echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV

    - name: Upload Debug APK
      id: apk_upload  # <--- Added ID to reference the link later
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/${{ env.APK_NAME }}

    - name: Send Pushover Notification
      if: always() # Runs even if the build fails
      run: |
        # 1. Determine Title and Priority
        if [ "${{ job.status }}" == "success" ]; then
          PRIORITY=0
          TITLE="${{ github.workflow }}: Success"
          MESSAGE="Branch: ${{ github.ref_name }}
          Status: ${{ job.status }}

          Download APK: ${{ steps.apk_upload.outputs.artifact-url }}"
        else
          PRIORITY=1
          TITLE="${{ github.workflow }}: Failed"
          MESSAGE="Branch: ${{ github.ref_name }}
          Status: ${{ job.status }}

          Download Logs: ${{ steps.log_upload.outputs.artifact-url }}"
        fi

        # 2. Send Notification
        # We include the specific Artifact URL in the message body
        curl -s \
          --form-string "token=${{ secrets.PUSHOVER_APP_TOKEN }}" \
          --form-string "user=${{ secrets.PUSHOVER_USER_KEY }}" \
          --form-string "title=$TITLE" \
          --form-string "priority=$PRIORITY" \
          --form-string "message=$MESSAGE" \
          --form-string "url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          https://api.pushover.net/1/messages.json
